# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1
command:
  print_pipeline_id:
    steps:
      - echo $CIRCLE_WORKFLOW_ID
jobs:
  print_command:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run:
        command: print_pipeline_id

workflows:
  my_workflow:
    jobs:
      - print_command
